# Generated by Django 4.2.16 on 2024-10-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbordapp', '0002_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='create',
        ),
        migrations.DeleteModel(
            name='update',
        ),
    ]
