# Generated by Django 4.2.16 on 2024-11-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('style', models.CharField(max_length=100, verbose_name='Style de produit')),
                ('materiau', models.CharField(max_length=100, verbose_name='Matériau')),
                ('image', models.ImageField(upload_to='produits/', verbose_name='Image du produit')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
    ]
